---
name: 'build JavaScript project'
description: 'Used by the SKNUPS organisation to build JavaScript projects'

inputs:
  skip_lint:
    description: "If 'true', do not execute 'npm run lint'"
    required: false
    default: 'false'
  skip_compile:
    description: "If 'true', do not execute 'npm run compile'"
    required: false
    default: 'false'
  skip_test:
    description: "If 'true', do not execute 'npm test'"
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:

    - name: Install Node.js v18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Configure npm
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/configure-npm.sh

    - name: Analyze dependencies
      id: 'dependencies'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/analyze-dependencies.sh

    - name: Authenticate Google Artifact Registry
      if: steps.dependencies.outputs.authenticate == 'true'
      uses: sknups/authenticate-google-artifact-registry-action@v1
      with:
        workload_identity_provider: 'projects/702125700768/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-provider'
        service_account: 'npm-internal-reader-gh@sknups.iam.gserviceaccount.com'

    - name: Install npm dependencies
      shell: bash
      run: npm ci

    - name: Execute ESLint
      if: ${{ inputs.skip_lint == 'false' }}
      shell: bash
      run: npm run lint

    - name: Execute Typescript compiler
      if: ${{ inputs.skip_compile == 'false' }}
      shell: bash
      run: npm run compile

    - name: Execute Jest
      if: ${{ inputs.skip_test == 'false' }}
      shell: bash
      run: npm test
